skycoin/hardware-wallet-daemon

.github/ISSUE_TEMPLATE/blank.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
=> setup github templates

src/api/README.md, src/api/apply_settings.go, src/api/apply_settings_test.go, swagger.yml
Related to #19 
Changes:
- Remove required check for `label` in `applySettings`
no
Requires changes in protobuf specs?
no
test updated
=> remove required param from label in apply settings

Gopkg.lock, Makefile, ci-scripts/integration-test.sh, src/api/csrf.go, src/api/csrf_test.go, src/api/http.go, src/api/http_test.go, src/api/integration/empty.go, src/api/integration/integration_test.go, src/api/transaction_sign_test.go, src/client/operations/post_apply_settings_parameters.go, src/daemon/config.go, src/daemon/daemon.go, src/models/c_s_r_f_response.go, swagger.yml, vendor/github.com/skycoin/hardware-wallet-go/.travis.yml, vendor/github.com/skycoin/hardware-wallet-go/CHANGELOG.md, vendor/github.com/skycoin/hardware-wallet-go/src/device-wallet/device-wallet.go, vendor/github.com/skycoin/hardware-wallet-go/src/device-wallet/integration/device_interface_test.go, vendor/github.com/skycoin/hardware-wallet-go/src/device-wallet/mock_devicer_test.go
Fixes #27 
Changes:
- Adds csrf header to integration tests
no
no
yes
Change is a test
=> add csrf integration tests

src/api/http.go, src/api/http_test.go, src/api/middleware.go
Fixes #30 
Changes:
- Allow requests from any localhost address
- Allow requests for `https://staging.wallet.skycoin.net` and `https://wallet.skycoin.net`
no
no
yes
tests added
=> fix-cors-policy

.travis.yml, Makefile, README.md, src/api/address_test.go, src/api/apply_settings_test.go, src/api/backup_test.go, src/api/cancel_test.go, src/api/check_message_signature_test.go, src/api/connected_test.go, src/api/csrf_test.go, src/api/features_test.go, src/api/firmware_update_test.go, src/api/gateway.go, src/api/generate_mnemonic_test.go, src/api/http.go, src/api/http_test.go, src/api/integration/integration_test.go, src/api/recovery_test.go, src/api/set_mnemonic_test.go, src/api/set_pin_code_test.go, src/api/sign_message_test.go, src/api/transaction_sign.go, src/api/transaction_sign_test.go, src/api/wipe_test.go, src/daemon/config.go, src/daemon/daemon.go
Fixes #25 
Changes:
- Add `-daemon-mode` flag to run daemon in `USB` or `EMULATOR` mode.
no
no
yes
tests updated
=> add flag to set daemon mode

Makefile, src/api/http.go, src/api/integration/integration_test.go
Fixes #45 
Changes:
- Replace `HandleFirmwareResponse` recursive function with a for loop implementation.
no
no
yes
Tested manually
=> remove recursive function

src/api/generate_mnemonic_test.go, src/api/http.go, src/api/http_test.go, src/api/middleware.go
Fixes #30 
Changes:
- fix incorrect regex
no
no
yes 
added test
=> fix cors regex

.travis.yml, Makefile, src/api/address.go, src/api/apply_settings.go, src/api/backup.go, src/api/cancel.go, src/api/check_message_signature.go, src/api/connected.go, src/api/features.go, src/api/generate_mnemonic.go, src/api/helper.go, src/api/http.go, src/api/intermediate.go, src/api/recovery.go, src/api/set_mnemonic.go, src/api/set_pin_code.go, src/api/sign_message.go, src/api/transaction_sign.go, src/api/wipe.go
Part of #44 
Changes:
- serialise daemon requests and cancel old request on incoming requests
no
Requires changes in protobuf specs?
no
tests already present
=> 44 fix close error

docker-compose.yml
Fixes #22 
Changes:
- Add `docker-compose.yml` for linux
no
no
no
Comments about testing , should you have some
=> add dockerfile

.travis.yml, Makefile, build/build-conf.sh, build/build-daemon-release.sh, build/package-daemon-release.sh, build/xgo.sh, ci-scripts/build-daemon.sh
Changes
- Update build scripts to handle os versions
no
no
no
=> Update build scripts

src/api/README.md, src/api/intermediate.go
Changes:
- Add firmware update and intermediate examples
no
no
no
=> add firmware and intermediate examples

src/api/address.go, src/api/apply_settings.go, src/api/backup.go, src/api/cancel.go, src/api/check_message_signature.go, src/api/configure_pin_code.go, src/api/features.go, src/api/generate_mnemonic.go, src/api/helper.go, src/api/intermediate.go, src/api/recovery.go, src/api/set_mnemonic.go, src/api/sign_message.go, src/api/transaction_sign.go, src/api/wipe.go
Changes:
- Remove request serialization
no
no
no
=> remove request serializaion

.travis.yml, build/build-conf.sh, build/build-daemon-release.sh, build/package-daemon-release.sh
Related to #64
Changes:
- Add deployment using travis
no
no
no
=> add travis deploy

.travis.yml
Fixes #64 
Changes:
- Add s3 deploy to travis
no
no
no
=> add s3 deploy to travis

src/api/apply_settings.go, src/api/helper.go
Fixes #84 
Changes:
- Fix HandleFirmwareResponse
no
no
no
=> fix handle firmware response

Makefile, build/compress-daemon-release.sh, build/linux/fpm.before-install.sh
Changes:
- Fix directory structure of linux packages
no
no
no
=> fix linux packaging

src/daemon/config.go
Changes:
- Fix http timeouts
no
no
no
=> fix timeouts

src/api/intermediate.go
Changes:
- Add missing return on 500 server error 
no
no
yes
existing tests shoud lpass
=> return on server error

build/compress-daemon-release.sh, build/package-daemon-release.sh
Changes:
- Fix rpm package build
no
no
no
=> fix linux builds

Gopkg.lock, src/daemon/config.go, vendor/github.com/skycoin/hardware-wallet-go/README.md, vendor/golang.org/x/sys/windows/service.go
Changes:
- Increase http timeouts
- update deps
no
no
yes 
Existing tests should pass
=> increase http timeouts

Gopkg.lock, src/api/address.go, src/api/apply_settings.go, src/api/backup.go, src/api/cancel.go, src/api/check_message_signature.go, src/api/configure_pin_code.go, src/api/features.go, src/api/firmware_update.go, src/api/generate_mnemonic.go, src/api/helper.go, src/api/http.go, src/api/intermediate.go, src/api/mock_gatewayer_test.go, src/api/recovery.go, src/api/set_mnemonic.go, src/api/sign_message.go, src/api/transaction_sign.go, src/api/wipe.go, src/daemon/config.go, src/daemon/daemon.go, vendor/github.com/skycoin/hardware-wallet-go/src/skywallet/skywallet.go, vendor/github.com/skycoin/hardware-wallet-go/src/skywallet/skywallet_test.go, vendor/github.com/skycoin/hardware-wallet-go/src/skywallet/usb/libusb.go
Fixes #103 
Changes:
- Handle request cancellation
no
no
yes
Existing tests should pass
=> 103 close device conn on cancel

src/api/address.go, src/api/apply_settings.go, src/api/backup.go, src/api/check_message_signature.go, src/api/configure_pin_code.go, src/api/features.go, src/api/firmware_update.go, src/api/intermediate.go, src/api/recovery.go, src/api/set_mnemonic.go, src/api/sign_message.go, src/api/transaction_sign.go, src/api/wipe.go
Changes:
- Fix error handling in response
no
no
yes
=> fix err handling

src/api/address.go, src/api/apply_settings.go, src/api/backup.go, src/api/check_message_signature.go, src/api/configure_pin_code.go, src/api/features.go, src/api/firmware_update.go, src/api/generate_mnemonic.go, src/api/intermediate.go, src/api/recovery.go, src/api/set_mnemonic.go, src/api/sign_message.go, src/api/transaction_sign.go, src/api/wipe.go
=> fix close conn on cancel
